### ISSUE TITLE
Question not really an issue

### ISSUE THREAD

**Issue by maheraldous** [sethdavis512/gatsby-keystone-shop#3]
Hello @sethdavis512 

Can you please make a tutorial about how you made this project. Step by step if you can. I am new to MongoDB, KeystoneJS and GatsbyJS. I came from Wordpress, WooCommerce, ReactJS, React Native, Expo, MySQL.
I spend weeks trying to follow tutorials from the internet but no one had everything I needed together as you did. :)

Thanks in advance

**Comment by sethdavis512** [comment]
I'm definitely open to this idea. I can't guarantee anything but I appreciate your interest in my work 😄

**Comment by maheraldous** [comment]
Can you at least tell me how did you connect Gatsby to KeystoneJS which plugin or how?

**Comment by sethdavis512** [comment]
Sure! You have to make Keystone aware that you'll be using a static app. [See here](https://github.com/sethdavis512/gatsby-keystone-shop/blob/master/index.js#L50) where I use [Keystone's `StaticApp`](https://www.keystonejs.com/keystonejs/app-static/) functionality.

**Comment by maheraldous** [comment]
Oh Thank you I will try it but in the KeystoneJS docs it says that fallback is "The path to the file to serve if none is found. This path is resolved relative to the src path." is that means that index.html is like 404.html page.

**Comment by maheraldous** [comment]
About the GraphQL both KeystoneJS and GatsbyJS have thier GrapQL URL when you lunch both separately so how do you merg them?

Sorry I won't ask more.

Thanks in advance

**Comment by sethdavis512** [comment]
>"The path to the file to serve if none is found. This path is resolved relative to the src path." is that means that index.html is like 404.html page.  

It doesn't have to be a 404 page, it can be whatever you'd like.

>About the GraphQL both KeystoneJS and GatsbyJS have thier GraphQL URL when you lunch both separately so how do you merge them?

You can have Gatsby proxy `localhost:3000`. Check out [this snippet of code](https://github.com/sethdavis512/gatsby-keystone-shop/blob/master/client/gatsby-config.js#L16) in my `gatsby.config.js`

Keep asking questions, I don't mind 👍

**Comment by sethdavis512** [comment]
Closing, reopen if you'd like.

**Comment by maheraldous** [comment]
Hello
Can I please get a copy of your .env file with sensitive data hidden? :)

**Comment by sethdavis512** [comment]
Sorry for the delay @maheraldous - Example `.env` has now been added to the README 🎉

**Comment by maheraldous** [comment]
Thank you @sethdavis512  :)
